Vagrant.configure("2") do |config|
  config.vm.define :web do |web|
    web.vm.box = "ubuntu/focal64"
    web.vm.network :private_network, ip: "10.0.0.10"
    web.vm.hostname = "web"
    web.vm.provision :shell, path: "web.sh"
  end

  config.vm.define :db do |db|
    db.vm.box = "ubuntu/focal64"
    db.vm.network :private_network, ip: "10.0.0.11"
    db.vm.hostname = "db"
    db.vm.provision :shell, path: "db.sh"
  end
end

#a VM ‘web’ terá o endereço IP 10.0.0.10 e a VM ‘db’ terá o endereço IP 10.0.0.11
# Você pode acessar cada VM pelo seu respectivo endereço IP a partir de qualquer outra VM